version: '3.8'

services:
  database:
    image: postgres:14.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eliana
      POSTGRES_DB: SistemiProgetto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./sistemi-distribuiti/sistemi-distribuiti
      dockerfile: Dockerfile
    container_name: spring_backend
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: SistemiProgetto
      DB_USERNAME: postgres
      DB_PASSWORD: eliana
      MAIL_USERNAME: domande.risposte.azienda@gmail.com
      MAIL_PASSWORD: wxizvxvrghpjphqm
      RESET_PASSWORD_URL: http://localhost:8080/reset-password
      HUGGINGFACE_API_URL: https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3
      HUGGINGFACE_ENDPOINT: https://router.huggingface.co/together/v1/chat/completions

  frontend:
    build:
      context: ./sistemi_distribuiti_front
      dockerfile: Dockerfile
    container_name: flutter_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "63569:80"

volumes:
  postgres_data:
